export interface CheckDefinition {
  checkId: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  regulationSection: string;
  fixInstructions: string;
  jobType: string;
}

export const CHECK_DEFINITIONS: CheckDefinition[] = [
  { checkId: "GWS-001", title: "MFA (2SV) Enforced for All Users", description: "Ensure that all non-suspended users have 2-Step Verification enabled and enforced.", severity: "critical", regulationSection: "CIS 1.3.1 | GDPR Art.32 | SOC2 CC6.1", fixInstructions: "Enable 2SV enforcement in Admin Console under Security > Authentication > 2-step verification.", jobType: "fetch_users_page" },
  { checkId: "GWS-002", title: "MFA Enforced for Admins with Security Keys", description: "Ensure admin accounts require hardware security keys for MFA.", severity: "critical", regulationSection: "CIS 1.3.2 | GDPR Art.5(1)(f),32 | SOC2 CC6.1,CC6.3", fixInstructions: "Configure admin OU to enforce security keys specifically in 2SV settings.", jobType: "fetch_users_page" },
  { checkId: "GWS-003", title: "Super Admin Count Limited (2-4)", description: "Maintain between 2 and 4 super admins.", severity: "high", regulationSection: "CIS 1.2.1 | GDPR Art.25(2),32 | SOC2 CC6.2,CC6.3", fixInstructions: "Review and revoke unnecessary super admin privileges.", jobType: "fetch_users_page" },
  { checkId: "GWS-004", title: "Separate Dedicated Admin Accounts", description: "Admin accounts should not be used for daily tasks.", severity: "high", regulationSection: "CIS 1.2.2 | GDPR Art.32 | SOC2 CC6.1,CC6.2", fixInstructions: "Create separate non-admin accounts for daily work.", jobType: "check_admin_activity" },
  { checkId: "GWS-005", title: "Inactive User Deprovisioning (90 Days)", description: "Users who have not logged in for 90 days should be suspended.", severity: "medium", regulationSection: "CIS 1.1.4 | GDPR Art.5(1)(e),32 | SOC2 CC6.2,CC6.3", fixInstructions: "Suspend accounts with no login activity over 90 days.", jobType: "fetch_users_page" },
  { checkId: "GWS-006", title: "Password Policy (Length >= 12)", description: "Enforce a minimum password length of 12 characters.", severity: "high", regulationSection: "CIS 1.1.1 | GDPR Art.32 | SOC2 CC6.1", fixInstructions: "Update password policy.", jobType: "check_admin_activity" },
  { checkId: "GWS-007", title: "Drive External Sharing Restricted", description: "Prevent sharing of internal documents with external domains.", severity: "high", regulationSection: "CIS 2.1.1 | GDPR Art.5(1)(f),32,44-49 | SOC2 CC6.6,CC6.7", fixInstructions: "Restrict external sharing in Drive settings.", jobType: "check_drive_sharing" },
  { checkId: "GWS-008", title: "Drive Public Link Sharing Disabled", description: "Ensure public link sharing is disabled.", severity: "critical", regulationSection: "CIS 2.1.2 | GDPR Art.32,33 | SOC2 CC6.6,CC6.7", fixInstructions: "Disable link sharing outside the organization.", jobType: "check_drive_sharing" },
  { checkId: "GWS-009", title: "Third-Party OAuth App Restrictions", description: "Restrict access to sensitive OAuth scopes by untrusted apps.", severity: "high", regulationSection: "CIS 5.1.1 | GDPR Art.28,32 | SOC2 CC6.1,CC6.3", fixInstructions: "Review OAuth app access.", jobType: "fetch_oauth_tokens" },
  { checkId: "GWS-010", title: "Suspicious Login Detection", description: "Monitor and alert on suspicious login events.", severity: "high", regulationSection: "CIS 6.1.1 | GDPR Art.33,34 | SOC2 CC7.2,CC7.3", fixInstructions: "Investigate suspicious login events.", jobType: "check_login_activity" },
  { checkId: "GWS-011", title: "SPF Record Configured", description: "Ensure SPF records are correctly configured.", severity: "high", regulationSection: "CIS 2.3.1 | GDPR Art.32 | SOC2 CC6.6,CC6.7", fixInstructions: "Add Google SPF include to domain DNS.", jobType: "check_email_dns" },
  { checkId: "GWS-012", title: "DKIM Signing Active", description: "Ensure outgoing emails are signed with DKIM.", severity: "high", regulationSection: "CIS 2.3.2 | GDPR Art.5(1)(f),32 | SOC2 CC6.6,CC6.7", fixInstructions: "Add DKIM keys to DNS and activate.", jobType: "check_email_dns" },
  { checkId: "GWS-013", title: "DMARC Policy Enforcement", description: "Ensure DMARC is configured with quarantine or reject.", severity: "medium", regulationSection: "CIS 2.3.3 | GDPR Art.32 | SOC2 CC6.6,CC6.8", fixInstructions: "Publish a DMARC record.", jobType: "check_email_dns" },
  { checkId: "GWS-014", title: "Mobile Device Security", description: "Ensure mobile device management is active.", severity: "high", regulationSection: "CIS 3.1.1 | GDPR Art.32(1)(a) | SOC2 CC6.1,CC6.6", fixInstructions: "Require screen locks and block compromised devices.", jobType: "fetch_mobile_devices" },
  { checkId: "GWS-015", title: "Google Groups External Restrictions", description: "Prevent external members in internal Google Groups.", severity: "medium", regulationSection: "CIS 4.1.1 | GDPR Art.5(1)(f),25 | SOC2 CC6.1,CC6.6", fixInstructions: "Update group settings.", jobType: "fetch_groups_settings" },
  { checkId: "GWS-016", title: "Calendar External Sharing Restricted", description: "Limit external calendar sharing.", severity: "medium", regulationSection: "CIS 2.2.1 | GDPR Art.5(1)(c) | SOC2 CC6.1,CC6.6", fixInstructions: "Adjust calendar settings.", jobType: "check_calendar_sharing" },
  { checkId: "GWS-017", title: "Admin Recovery Contact Hygiene", description: "Admins should not use consumer email domains for recovery contacts.", severity: "medium", regulationSection: "CIS 1.1.5 | GDPR Art.32 | SOC2 CC6.1,CC6.2", fixInstructions: "Remove consumer emails.", jobType: "fetch_users_page" },
  { checkId: "GWS-018", title: "Web Session Duration Controls", description: "Configure appropriate web session timeouts.", severity: "medium", regulationSection: "CIS 1.3.4 | GDPR Art.32 | SOC2 CC6.1,CC6.3", fixInstructions: "Set session length controls.", jobType: "check_admin_activity" },
  { checkId: "GWS-019", title: "Delegated Admin Roles Least Privilege", description: "Ensure custom admin roles follow least privilege.", severity: "high", regulationSection: "CIS 1.2.3 | GDPR Art.25(2),32 | SOC2 CC6.2,CC6.3", fixInstructions: "Review custom roles.", jobType: "check_admin_roles" },
  { checkId: "GWS-020", title: "DLP Rules Configured and Monitored", description: "Ensure Data Loss Prevention rules are active.", severity: "critical", regulationSection: "CIS 2.1.3 | GDPR Art.5(1)(f),25,32,33 | SOC2 CC6.7,CC7.2,CC7.3", fixInstructions: "Create DLP rules.", jobType: "check_dlp_rules" }
];
