// Database Audit Check Definitions
// 10 PostgreSQL checks + 10 MySQL checks
// Mapped to CIS DB Benchmarks, PCI DSS (2.3, 8.2, 10.2), HIPAA §164.312

export interface DbCheckDefinition {
  checkId: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  regulationSection: string;
  fixInstructions: string;
  engine: 'postgres' | 'mysql';
  queryKey: string; // key in the agent payload that provides the raw data
}

export const DB_CHECK_DEFINITIONS: DbCheckDefinition[] = [
  // ── PostgreSQL Checks (PG-001 through PG-010) ──────────────────────

  {
    checkId: 'PG-001',
    title: 'Password Encryption uses scram-sha-256',
    description: 'Ensure password_encryption is set to scram-sha-256 for strong credential hashing.',
    severity: 'critical',
    regulationSection: 'CIS PostgreSQL 3.2 | PCI DSS 8.2.1 | HIPAA §164.312(a)(2)(iv)',
    fixInstructions: "Set password_encryption = 'scram-sha-256' in postgresql.conf and reload.",
    engine: 'postgres',
    queryKey: 'password_encryption',
  },
  {
    checkId: 'PG-002',
    title: 'No Trust Authentication in pg_hba.conf',
    description: 'Ensure pg_hba.conf does not contain any "trust" authentication entries.',
    severity: 'critical',
    regulationSection: 'CIS PostgreSQL 3.1 | PCI DSS 8.2.1 | HIPAA §164.312(d)',
    fixInstructions: 'Remove all lines with auth_method = "trust" from pg_hba.conf and reload.',
    engine: 'postgres',
    queryKey: 'pg_hba_rules',
  },
  {
    checkId: 'PG-003',
    title: 'SSL Enforced for All Connections',
    description: 'Ensure ssl = on to encrypt data in transit.',
    severity: 'high',
    regulationSection: 'CIS PostgreSQL 6.8 | PCI DSS 2.3 | HIPAA §164.312(e)(1)',
    fixInstructions: "Set ssl = on in postgresql.conf and configure ssl_cert_file / ssl_key_file.",
    engine: 'postgres',
    queryKey: 'ssl_setting',
  },
  {
    checkId: 'PG-004',
    title: 'Connection Logging Enabled',
    description: 'Ensure log_connections and log_disconnections are both ON.',
    severity: 'high',
    regulationSection: 'CIS PostgreSQL 4.1 | PCI DSS 10.2.1 | HIPAA §164.312(b)',
    fixInstructions: 'Set log_connections = on and log_disconnections = on in postgresql.conf.',
    engine: 'postgres',
    queryKey: 'log_connections',
  },
  {
    checkId: 'PG-005',
    title: 'Statement Logging Configured',
    description: 'Ensure log_statement is set to at least "ddl" to capture schema changes.',
    severity: 'medium',
    regulationSection: 'CIS PostgreSQL 4.2 | PCI DSS 10.2.2 | HIPAA §164.312(b)',
    fixInstructions: "Set log_statement = 'ddl' or 'all' in postgresql.conf.",
    engine: 'postgres',
    queryKey: 'log_statement',
  },
  {
    checkId: 'PG-006',
    title: 'Superuser Count ≤ 2',
    description: 'Minimize the number of superuser roles to reduce blast radius.',
    severity: 'high',
    regulationSection: 'CIS PostgreSQL 2.1 | PCI DSS 8.2.2 | HIPAA §164.312(a)(1)',
    fixInstructions: 'Revoke superuser from unnecessary roles. Maintain only 1-2 superusers.',
    engine: 'postgres',
    queryKey: 'superusers',
  },
  {
    checkId: 'PG-007',
    title: 'PUBLIC Schema CREATE Privilege Revoked',
    description: 'Ensure the PUBLIC role has no CREATE privilege on the public schema.',
    severity: 'high',
    regulationSection: 'CIS PostgreSQL 2.3 | PCI DSS 8.2.2 | HIPAA §164.312(a)(1)',
    fixInstructions: 'Run: REVOKE CREATE ON SCHEMA public FROM PUBLIC;',
    engine: 'postgres',
    queryKey: 'public_schema_privs',
  },
  {
    checkId: 'PG-008',
    title: 'No Roles with NULL Passwords',
    description: 'Ensure all login-capable roles have a password set.',
    severity: 'critical',
    regulationSection: 'CIS PostgreSQL 3.3 | PCI DSS 8.2.1 | HIPAA §164.312(d)',
    fixInstructions: 'Set passwords for all login roles or disable login: ALTER ROLE x NOLOGIN;',
    engine: 'postgres',
    queryKey: 'null_password_roles',
  },
  {
    checkId: 'PG-009',
    title: 'CREATEDB / CREATEROLE Privilege Review',
    description: 'Only intended roles should have CREATEDB or CREATEROLE privileges.',
    severity: 'medium',
    regulationSection: 'CIS PostgreSQL 2.2 | PCI DSS 8.2.2 | HIPAA §164.312(a)(1)',
    fixInstructions: 'Revoke CREATEDB/CREATEROLE from roles that do not need them.',
    engine: 'postgres',
    queryKey: 'privileged_roles',
  },
  {
    checkId: 'PG-010',
    title: 'pgaudit Extension Installed',
    description: 'Ensure the pgaudit extension is installed for detailed audit logging.',
    severity: 'medium',
    regulationSection: 'CIS PostgreSQL 4.3 | PCI DSS 10.2 | HIPAA §164.312(b)',
    fixInstructions: "Run: CREATE EXTENSION IF NOT EXISTS pgaudit; Configure pgaudit.log = 'all'.",
    engine: 'postgres',
    queryKey: 'extensions',
  },

  // ── MySQL Checks (MY-001 through MY-010) ───────────────────────────

  {
    checkId: 'MY-001',
    title: 'Root Account Restricted to Localhost',
    description: "Ensure the root user can only connect from localhost / 127.0.0.1.",
    severity: 'critical',
    regulationSection: 'CIS MySQL 4.2 | PCI DSS 8.2.1 | HIPAA §164.312(d)',
    fixInstructions: "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost','127.0.0.1','::1'); FLUSH PRIVILEGES;",
    engine: 'mysql',
    queryKey: 'root_hosts',
  },
  {
    checkId: 'MY-002',
    title: 'No Anonymous User Accounts',
    description: "Ensure there are no accounts with an empty User field.",
    severity: 'critical',
    regulationSection: 'CIS MySQL 4.1 | PCI DSS 8.2.1 | HIPAA §164.312(d)',
    fixInstructions: "DROP USER ''@'localhost'; DROP USER ''@'%'; FLUSH PRIVILEGES;",
    engine: 'mysql',
    queryKey: 'anonymous_users',
  },
  {
    checkId: 'MY-003',
    title: "No 'test' Database Present",
    description: "The default 'test' database should be removed in production.",
    severity: 'medium',
    regulationSection: 'CIS MySQL 1.3 | PCI DSS 2.3 | HIPAA §164.312(a)(1)',
    fixInstructions: "DROP DATABASE IF EXISTS test;",
    engine: 'mysql',
    queryKey: 'test_database',
  },
  {
    checkId: 'MY-004',
    title: 'validate_password Plugin Active',
    description: 'Ensure the validate_password component/plugin is installed and active.',
    severity: 'high',
    regulationSection: 'CIS MySQL 6.1 | PCI DSS 8.2.1 | HIPAA §164.312(a)(2)(iv)',
    fixInstructions: "INSTALL COMPONENT 'file://component_validate_password'; or INSTALL PLUGIN validate_password SONAME 'validate_password.so';",
    engine: 'mysql',
    queryKey: 'validate_password',
  },
  {
    checkId: 'MY-005',
    title: 'local_infile Disabled',
    description: 'Ensure local_infile is OFF to prevent loading local files into the server.',
    severity: 'high',
    regulationSection: 'CIS MySQL 5.1 | PCI DSS 2.3 | HIPAA §164.312(a)(1)',
    fixInstructions: "SET GLOBAL local_infile = OFF; Add local_infile=0 to my.cnf.",
    engine: 'mysql',
    queryKey: 'local_infile',
  },
  {
    checkId: 'MY-006',
    title: 'require_secure_transport Enabled',
    description: 'Ensure SSL/TLS is required for all client connections.',
    severity: 'high',
    regulationSection: 'CIS MySQL 6.3 | PCI DSS 2.3 | HIPAA §164.312(e)(1)',
    fixInstructions: "SET GLOBAL require_secure_transport = ON; Add require_secure_transport=ON to my.cnf.",
    engine: 'mysql',
    queryKey: 'require_secure_transport',
  },
  {
    checkId: 'MY-007',
    title: 'General Log or Audit Plugin Enabled',
    description: 'Ensure either general_log is ON or an audit plugin (audit_log) is active.',
    severity: 'medium',
    regulationSection: 'CIS MySQL 5.4 | PCI DSS 10.2 | HIPAA §164.312(b)',
    fixInstructions: "SET GLOBAL general_log = ON; or install MySQL Enterprise Audit plugin.",
    engine: 'mysql',
    queryKey: 'audit_logging',
  },
  {
    checkId: 'MY-008',
    title: 'secure_file_priv Not Empty',
    description: 'Ensure secure_file_priv is set to a specific directory (not empty/NULL).',
    severity: 'high',
    regulationSection: 'CIS MySQL 5.2 | PCI DSS 2.3 | HIPAA §164.312(a)(1)',
    fixInstructions: "Set secure_file_priv to a specific directory in my.cnf, e.g. secure_file_priv='/var/lib/mysql-files/'.",
    engine: 'mysql',
    queryKey: 'secure_file_priv',
  },
  {
    checkId: 'MY-009',
    title: 'No Non-Admin Users with GRANT ALL',
    description: 'Ensure no non-root/non-admin users have been granted ALL PRIVILEGES.',
    severity: 'high',
    regulationSection: 'CIS MySQL 4.3 | PCI DSS 8.2.2 | HIPAA §164.312(a)(1)',
    fixInstructions: 'Revoke ALL PRIVILEGES from non-admin users and grant only required privileges.',
    engine: 'mysql',
    queryKey: 'grant_all_users',
  },
  {
    checkId: 'MY-010',
    title: 'Minimize mysql_native_password Usage',
    description: 'Prefer caching_sha2_password over mysql_native_password for stronger auth.',
    severity: 'medium',
    regulationSection: 'CIS MySQL 6.2 | PCI DSS 8.2.1 | HIPAA §164.312(a)(2)(iv)',
    fixInstructions: "ALTER USER 'user'@'host' IDENTIFIED WITH caching_sha2_password BY 'newpass';",
    engine: 'mysql',
    queryKey: 'native_password_users',
  },
];
